// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX6Evwe6McT9krV3u6yJ1ia4NsPjs1Goo',
    appId: '1:920543527292:web:a864ce0232e171c741e4f9',
    messagingSenderId: '920543527292',
    projectId: 'pulse-talk-7a5b2',
    authDomain: 'pulse-talk-7a5b2.firebaseapp.com',
    storageBucket: 'pulse-talk-7a5b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPxoXetqRMsH6ZqeBVyhJJWQkKYLST520',
    appId: '1:920543527292:android:a35ad95e8f6e044941e4f9',
    messagingSenderId: '920543527292',
    projectId: 'pulse-talk-7a5b2',
    storageBucket: 'pulse-talk-7a5b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeMclqPwgIvP025c9UMd089HwCCkS3-DQ',
    appId: '1:920543527292:ios:ea93ea8be1d6248841e4f9',
    messagingSenderId: '920543527292',
    projectId: 'pulse-talk-7a5b2',
    storageBucket: 'pulse-talk-7a5b2.appspot.com',
    iosBundleId: 'com.example.pulseTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeMclqPwgIvP025c9UMd089HwCCkS3-DQ',
    appId: '1:920543527292:ios:c96a96b58f1ff62841e4f9',
    messagingSenderId: '920543527292',
    projectId: 'pulse-talk-7a5b2',
    storageBucket: 'pulse-talk-7a5b2.appspot.com',
    iosBundleId: 'com.example.pulseTalk.RunnerTests',
  );
}
